#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries in GRUB.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Windows_10' {
	#search --fs-uuid --no-floppy --set=root 9f4d5943-0038-42c5-9feb-4550b4270b91
	search --fs-uuid --no-floppy --set=root 52c3-7a47
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
